# server
server:
  port: 8081
  servlet:
    context-path: /

spring:
  operatelog:
    log-type: other
    handler: io.github.panxiaochao.system.application.event.OperateLogEventHandler
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: pxc-system-api
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/pxc-system?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 60000
      connection-timeout: 30000
      pool-name: pxc-system-pool
  # Redis
  redis:
    url: 127.0.0.1
    port: 6379
    database: 0
  # 是否开启跨域
  pxc-web:
    cors: true

# mybatis-plus 配置
mybatis-plus:
  db-type: mysql
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    # 开发测试时使用
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 登录获取 token 地址
pxc-auth:
  url: http://localhost:18000/oauth2/v1/token
