# server
server:
  port: 8081
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: pxc-system
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/pxc-system?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      pool-name: pxc-system-pool
  # Redis
  redis:
    url: 127.0.0.1
    port: 6379
    database: 0

  # 开启框架配置
  pxc-framework:
    # 是否开启异步
    async: true
    # 是否开启跨域
    cors:
      enable: true
    # 开启XSS防护
    xss:
      enable: false
    operatelog:
      log-type: other
      handler: io.github.panxiaochao.system.application.event.OperateLogEventHandler
    auth:
      white-urls:
        - /web/v1/login
        - /web/v1/logout
        - /system/v1/sysuser/**
        - /system/v1/syspost/**
        - /system/v1/sysorg/**
        - /system/v1/sysuserrole/**
        - /system/v1/sysrole/**
        - /system/v1/sysarea/**
        - /system/v1/syslogoperate/**
        - /system/v1/sysloglogin/**
        - /system/v1/sysdict/**
        - /system/v1/sysdictitem/**
        - /system/v1/sysparam/**
        - /web/v1/server/**
        - /web/v1/redis/**
        - /web/v1/token/**
        - /system/v1/systenant/**
        - /system/v1/systenantpackage/**
        - /system/v1/systenantpackagemenu/**
      algorithm: rs512
      token-style: simple_uuid


# mybatis-plus 配置
mybatis-plus:
  db-type: mysql
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    # 开发测试时使用
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 暴露指标
#management:
#  endpoint:
#    health:
#      enabled: false
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#        exclude: "*"
#    jmx:
#      exposure:
#        include: "*"
#        exclude: "*"
