# server
server:
  port: 8081
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: pxc-system
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/pxc-system?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      pool-name: pxc-system-pool
  # Redis
  redis:
    url: 127.0.0.1
    port: 6379
    database: 0

  # 开启框架配置
  pxc-framework:
    dynamic:
      query-ds-sql: "SELECT db_code `name`, db_jdbc_url 'url', db_username 'username', db_password 'password' FROM database_source"
    # 是否开启异步
    async: true
    # 是否开启跨域
    cors:
      enabled: true
    # 开启XSS防护
    xss:
      enabled: false
    operatelog:
      log-type: other
      handler: io.github.panxiaochao.system.application.event.OperateLogEventHandler

# mybatis-plus 配置
mybatis-plus:
  db-type: mysql
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    # 开发测试时使用
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
