# server
server:
  port: 8081
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: pxc-system
  # 数据库
  datasource:
    url: jdbc:mysql://localhost:3306/pxc-system?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      pool-name: pxc-system-pool
  # Redis
  redis:
    url: 127.0.0.1
    port: 6379
    database: 0

  # 开启框架配置
  pxc-framework:
    dynamic:
      query-ds-sql: "SELECT db_code `name`, db_jdbc_url 'url', db_username 'username', db_password 'password' FROM database_source"
    # 是否开启异步
    async: true
    # 是否开启跨域
    cors:
      enabled: true
    # 开启XSS防护
    xss:
      enabled: false
    operatelog:
      log-type: other
      handler: io.github.panxiaochao.system.event.OperateLogEventHandler

# mybatis-plus 配置
mybatis-plus:
  db-type: mysql
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    # 开发测试时使用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # jwt秘钥
  jwt-secret-key: pxc-system-cloud
  # 请求 token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认2小时，-1 代表永久有效
  timeout: 7200
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-64
  # 是否输出操作日志
  is-log: false
  # 是否在初始化配置时打印版本字符画
  is-print: false
  # 是否尝试从header里读取token
#  is-read-header: true
  # 是否尝试从cookie里读取token
#  is-read-cookie: false
  # token前缀
  token-prefix: Bearer
  # 白名单 URL
  white-urls:
    - /web/v1/login
    - /system/v1/**
